### ISSUE TITLE
Can't replay example in README

### ISSUE THREAD

**Issue by marcovc** [gnosis/contract-proxy-kit#78]
Hi,

I'm trying to replay the "approve" example in the README (I'm with version 1.1.1 on Kovan).

Doing the transaction directly works:
```
    const spender = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    const allowance = web3.utils.toWei("0.01")

    const result1 = await weth.methods.approve(spender, allowance).send({
        from: web3.eth.defaultAccount,
        gas: GAS
    })
    console.log(result1)
```

This doesn't:
```
    const cpk = await CPK.create({web3})
    const tx = [{
        operation: CPK.CALL,
        value: 0,
        to: weth.options.address,
        data: weth.methods.approve(
            spender,
            allowance
        ).encodeABI()
    }]
    await cpk.execTransactions(tx, {gas: GAS})
```

failing with something that does not help much:

```
node_modules/web3-core-helpers/src/errors.js:29
        return new Error('Returned error: ' + message);
               ^

Error: Returned error: VM execution error.
    at Object.ErrorResponse (node_modules/web3-core-helpers/src/errors.js:29:16)
    at node_modules/web3-core-requestmanager/src/index.js:170:36
    at XMLHttpRequest.request.onreadystatechange (node_modules/web3-providers-http/src/index.js:111:13)
    at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Is there something obvious I might be missing?

Thanks!
Marco

**Comment by marcovc** [comment]
It turned out this horrific message was just caused by lack of gas. Closing.
